version: '3'

networks:
  my-network:
    driver: bridge
    

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: masterpassword
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my-network

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: slavepassword
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/conf:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my-network